
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER2_H
#define MASTER2_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master2_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master2_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data Master2_Data;

#endif // MASTER_H
